google: mark cache as ready after it got populated
canonical/spread pull request #175
Opened 2023-10-13 09:54 UTC by mvo5

The googleImagesCache is currently not marked `ready` AFAICT. This means while it is correctly build it is not used in subsequent calls to projectImages(). This commit set the cache to ready after it got populated.

Setting to draft right now as it needs a test.

2024-12-05 16:54 UTC, cmatsuoka approved these changes

2024-12-09 15:30 UTC, niemeyer requested changes
Thanks for the PR. Claudio, can we please have a look at these details?

2024-12-09 16:15 UTC, niemeyer approved these changes
Thanks everyone.

2024-12-09 16:16 UTC, mvo5 commented
Super nice to see this getting in, thank you so much @niemeyer and @cmatsuoka

2024-12-09 16:56 UTC, merged