spread: work around SSH password authentication disabled by livecd-rootfs
canonical/spread pull request #184
Opened 2024-03-13 14:43 UTC by bboozzoo

In recent images, livecd-rootfs may be disabling SSH password authentication by default, with the intention that cloud-init would enabled that by placing a higher priority file under /etc/sshd/sshd_config.d/. See https://git.launchpad.net/livecd-rootfs/commit/live-build/ubuntu-cpc/hooks.d/chroot/052-ssh_authentication.chroot?id=480d5b26ea97e0bfebac8aedfa1f2bf7286f027a for reference.

Do the same as cloud-init would a drop a higher priority config overriding relevant SSHD settings.

2024-03-13 14:51 UTC, zyga approved these changes
This looks good to me.

2024-03-13 14:55 UTC, bboozzoo commented
I'll extend the lxd backend spread test to cover more recent images.

2024-03-13 15:14 UTC, bboozzoo commented
LXD backend spread tests have been updated with Ubuntu 18.04, 20.04, and 22.04.

2024-03-13 15:23 UTC, bboozzoo commented
Looks like a similar fix but done slightly differently was proposed in #179

2024-03-14 06:47 UTC, thp-canonical commented
Also related, a similar fix for the Google backend: #155

2024-03-19 10:41 UTC, ZeyadYasser reviewed
Thank you for catching this, Maybe let's wait for it to be merged in the google backend https://github.com/snapcore/spread/pull/155? and then backport it to all other providers so that it is consistent across all of them.

2024-12-05 14:58 UTC, cmatsuoka approved these changes
Thanks!

2024-12-09 15:13 UTC, niemeyer requested changes
Thanks for the PR. Seems reasonable, but a bit obscure. More details below.

2024-12-09 15:28 UTC, bboozzoo commented on spread/lxd.go
> +		{"/bin/bash", "-c", `[ -d /etc/ssh/sshd_config.d ] && echo -e "PermitRootLogin yes\nPasswordAuthentication yes" > /etc/ssh/sshd_config.d/00-spread.conf`},
I have tweaked the wording around the snippets.

2024-12-09 19:31 UTC, cmatsuoka commented on spread/lxd.go
> +		{"/bin/bash", "-c", `[ -d /etc/ssh/sshd_config.d ] && echo -e "PermitRootLogin yes\nPasswordAuthentication yes" > /etc/ssh/sshd_config.d/00-spread.conf`},
Thanks for the update. It's better not to force-push after the review started to preserve the dialogue in PR comments (the final landing is squashed so intermediate commits won't appear in the git history anyway). That said, I think the comment wording is still a bit confusing. Let me try an alternative.

2024-12-11 14:33 UTC, niemeyer approved these changes
Thanks!

2024-12-11 14:34 UTC, niemeyer commented
Oops, tests are failing.

2024-12-11 15:09 UTC, bboozzoo commented on spread/lxd.go
> +		{"/bin/bash", "-c", `[ -d /etc/ssh/sshd_config.d ] && echo -e "PermitRootLogin yes\nPasswordAuthentication yes" > /etc/ssh/sshd_config.d/00-spread.conf`},
The 'shortened' version is actually wrong, exit code `[ -d /etc/ssh/sshd_config.d ]` becomes the return status of the whole command. Let me push a fix.

2024-12-11 16:07 UTC, bboozzoo commented
I don't think this is getting anywhere given the flakiness in lxd:
```                                        
Error: Failed instance creation: write unix @->/var/snap/lxd/common/lxd/unix.socket: i/o timeout
-----
```

2024-12-16 15:50 UTC, merged